# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.bicLogLik <- function(argY, argTheta, argPii, argSigma, argIndex) {
    .Call('_GroupSortFuse2_bicLogLik', PACKAGE = 'GroupSortFuse2', argY, argTheta, argPii, argSigma, argIndex)
}

.myEm <- function(argY, argm, argTheta, argSigma, argPii, argArbSigma, argM, argIndex, argMaxAdmm, argCk, argA, argPenalty, argLambdaVals, argEpsilon, argMaxRep, argDelta, argVerbose) {
    .Call('_GroupSortFuse2_myEm', PACKAGE = 'GroupSortFuse2', argY, argm, argTheta, argSigma, argPii, argArbSigma, argM, argIndex, argMaxAdmm, argCk, argA, argPenalty, argLambdaVals, argEpsilon, argMaxRep, argDelta, argVerbose)
}

